# Site settings
title:       Caio Yassoyama
email:       caio.yassoyama@gmail.com
author:      Caio Yassoyama
description: "About Android programming"
baseurl:     ""
url:         "http://caioyassoyama.github.io"

# Google analytics
google_analytics: UA-57913256-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: caioyassoyama

# Social icons
show_social_icons: true
github_username: caioyassoyama
stackoverflow_id: 2001471
twitter_username: caioyassoyama
google_plus_id: +CaioYassoyama
linkedin_username: caioyassoyama
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
